# Generated by Django 3.1.5 on 2021-03-13 14:15

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20201015_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfilecontent',
            name='file',
            field=models.ImageField(upload_to=post.models.user_directory_path),
        ),
    ]
